var date = new Date();
var today = +date.getDate()+'/'+(date.getMonth()+1)+'/'+date.getFullYear();
document.getElementById('date').innerHTML= today;
var time = date.getHours() + ":" + date.getMinutes() + ":" + date.getSeconds();
document.getElementById('time').innerHTML= time;
var today1 =+date.getDate()+'/'+(date.getMonth()+1)+'/'+date.getFullYear();
document.getElementById('date1').innerHTML=today1;
var t1 = date.getHours() + ":" + date.getMinutes() + ":" + date.getSeconds();
document.getElementById('time1').innerHTML= t1; 
